using System;
using System.Collections.Generic;
using UnityEngine;

namespace KSPTethers
{
    /// <summary>
    /// How a cable looks and how stiff it is. Defined by CABLE_STYLE nodes in Settings.cfg. The surface is
    /// generated by <see cref="CablePatterns"/> from the style's TEXTURE node unless explicit texture paths
    /// are given.
    /// </summary>
    internal sealed class CableStyle
    {
        public string Name = "umbilical";
        public string Title = "White Umbilical";
        public string Description = "";
        public CableTextureSpec Texture = new CableTextureSpec();

        /// <summary>Half the cable's diameter, or half a flat strap's width.</summary>
        public float Radius = 0.022f;
        /// <summary>Flat straps only: thickness as a fraction of the width.</summary>
        public float Aspect = 0.18f;
        /// <summary>Texture tiles per metre of cable. Zero means "work it out from the diameter".</summary>
        public float TilesPerMeter;
        public float Gloss = 34f;
        public bool Metal;
        public Color Tint = Color.white;
        public Color FittingColor = new Color(0.55f, 0.57f, 0.60f, 1f);
        public float BendStiffness = 0.05f;
        public float MinBendRadius = 0.45f;
        public string TexturePath = "";
        public string NormalPath = "";

        private Material rope;
        private Material fitting;
        private Texture2D albedoTex;
        private Texture2D normalTex;

        public bool Flat => Texture.Flat;

        /// <summary>The swatch colour shown in the app, and the tint under the generated texture.</summary>
        public Color SwatchColor => Texture.Colour;

        public Material RopeMaterial
        {
            get { if (rope == null) rope = CreateRope(); return rope; }
        }

        public Material FittingMaterial
        {
            get { if (fitting == null) fitting = CreateFitting(); return fitting; }
        }

        /// <summary>Tiles per metre, worked out from the size when the config doesn't say.</summary>
        public float Tiling
        {
            get
            {
                if (TilesPerMeter > 0f)
                    return TilesPerMeter;
                // One tile is two circumferences long (two strap widths for a flat tether), which keeps the
                // generated texels square.
                float tile = Flat ? 4f * Radius : 4f * Mathf.PI * Radius;
                return tile > 1e-4f ? 1f / tile : 7f;
            }
        }

        /// <summary>Builds the textures now rather than on the frame the style is first drawn.</summary>
        public void Prewarm()
        {
            Material unused = RopeMaterial;
        }

        public static CableStyle FromNode(ConfigNode n)
        {
            var s = new CableStyle();
            n.TryGetValue("name", ref s.Name);
            s.Title = s.Name;
            n.TryGetValue("title", ref s.Title);
            n.TryGetValue("description", ref s.Description);
            n.TryGetValue("radius", ref s.Radius);
            n.TryGetValue("aspect", ref s.Aspect);
            n.TryGetValue("tilesPerMeter", ref s.TilesPerMeter);
            n.TryGetValue("gloss", ref s.Gloss);
            n.TryGetValue("metal", ref s.Metal);
            n.TryGetValue("tint", ref s.Tint);
            n.TryGetValue("fittingColor", ref s.FittingColor);
            n.TryGetValue("bendStiffness", ref s.BendStiffness);
            n.TryGetValue("minBendRadius", ref s.MinBendRadius);
            n.TryGetValue("texture", ref s.TexturePath);
            n.TryGetValue("normalMap", ref s.NormalPath);

            CableTextureSpec t = s.Texture;
            t.Construction = CablePatterns.ParseConstruction(n.GetValue("construction") ?? n.GetValue("pattern"), t.Construction);
            n.TryGetValue("flat", ref t.Flat);
            n.TryGetValue("seed", ref t.Seed);
            ConfigNode tn = n.GetNode("TEXTURE") ?? n;
            ReadTexture(tn, t);

            s.Radius = Mathf.Clamp(s.Radius, 0.003f, 0.2f);
            s.Aspect = Mathf.Clamp(s.Aspect, 0.05f, 1f);
            s.TilesPerMeter = Mathf.Clamp(s.TilesPerMeter, 0f, 200f);
            s.Gloss = Mathf.Clamp(s.Gloss, 1f, 100f);
            s.BendStiffness = Mathf.Clamp01(s.BendStiffness);
            s.MinBendRadius = Mathf.Clamp(s.MinBendRadius, 0f, 5f);
            return s;
        }

        private static void ReadTexture(ConfigNode n, CableTextureSpec t)
        {
            // The generator's own settings are read by name, so the game and the offline renders agree.
            foreach (ConfigNode.Value v in n.values)
                t.Set(v.name, v.value);

            ConfigNode[] stripes = n.GetNodes("STRIPE");
            if (stripes != null && stripes.Length > 0)
            {
                var list = new List<WeaveStripe>();
                foreach (ConfigNode sn in stripes)
                {
                    var st = new WeaveStripe { Colour = Color.black };
                    float from = 0f, to = 0f;
                    sn.TryGetValue("from", ref from);
                    sn.TryGetValue("to", ref to);
                    sn.TryGetValue("color", ref st.Colour);
                    st.From = from;
                    st.To = to;
                    if (to > from)
                        list.Add(st);
                }
                t.Stripes = list.Count > 0 ? list.ToArray() : null;
            }
        }

        private Material CreateRope()
        {
            Shader shader = CableStyles.FindShader("KSP/Bumped Specular", "KSP/Specular", "KSP/Diffuse", "Standard", "Diffuse");
            var m = new Material(shader) { name = "KSPTethers-" + Name };
            BuildTextures();
            SetTexture(m, "_MainTex", albedoTex);
            if (normalTex != null && m.HasProperty("_BumpMap"))
            {
                m.SetTexture("_BumpMap", normalTex);
                m.EnableKeyword("_NORMALMAP");
            }
            // The generated map already carries the colour and the baked cavity shading, so the tint is white
            // unless a style asks for one.
            SetColor(m, "_Color", Tint);
            Color spec = Metal
                ? new Color(Texture.Colour.r * 0.9f + 0.1f, Texture.Colour.g * 0.9f + 0.1f, Texture.Colour.b * 0.9f + 0.1f, 1f)
                : new Color(0.75f, 0.75f, 0.75f, 1f);
            SetColor(m, "_SpecColor", spec);
            SetFloat(m, "_Shininess", Mathf.Clamp(Gloss / 100f, 0.03f, 1f));
            SetFloat(m, "_Glossiness", Mathf.Clamp01(Gloss / 100f));
            SetFloat(m, "_Metallic", Metal ? 0.85f : 0.05f);
            SetFloat(m, "_Opacity", 1f);
            return m;
        }

        private void BuildTextures()
        {
            if (!string.IsNullOrEmpty(TexturePath) && GameDatabase.Instance != null && GameDatabase.Instance.ExistsTexture(TexturePath))
            {
                albedoTex = GameDatabase.Instance.GetTexture(TexturePath, false);
                if (!string.IsNullOrEmpty(NormalPath) && GameDatabase.Instance.ExistsTexture(NormalPath))
                    normalTex = GameDatabase.Instance.GetTexture(NormalPath, true);
                if (albedoTex != null)
                    return;
            }
            Color32[] main, normal;
            int w, h;
            CablePatterns.Generate(Texture, TetherConfig.Instance.textureSize, out main, out normal, out w, out h);
            albedoTex = MakeTexture(main, w, h, "KSPTethers-" + Name, false);
            normalTex = MakeTexture(normal, w, h, "KSPTethers-" + Name + "-Normal", true);
        }

        private static Texture2D MakeTexture(Color32[] pixels, int w, int h, string name, bool linear)
        {
            var t = new Texture2D(w, h, TextureFormat.RGBA32, true, linear)
            {
                name = name,
                wrapMode = TextureWrapMode.Repeat,
                filterMode = FilterMode.Trilinear,
                anisoLevel = 8
            };
            t.SetPixels32(pixels);
            t.Apply(true, true);
            return t;
        }

        private Material CreateFitting()
        {
            Shader shader = CableStyles.FindShader("KSP/Specular", "KSP/Diffuse", "Standard", "Diffuse");
            var m = new Material(shader) { name = "KSPTethers-" + Name + "-Fitting" };
            SetTexture(m, "_MainTex", CableStyles.White);
            SetColor(m, "_Color", FittingColor);
            SetColor(m, "_SpecColor", new Color(0.8f, 0.8f, 0.8f, 1f));
            SetFloat(m, "_Shininess", 0.55f);
            SetFloat(m, "_Glossiness", 0.7f);
            SetFloat(m, "_Metallic", 0.8f);
            SetFloat(m, "_Opacity", 1f);
            return m;
        }

        private static void SetTexture(Material m, string prop, Texture t)
        {
            if (t != null && m.HasProperty(prop)) m.SetTexture(prop, t);
        }

        private static void SetColor(Material m, string prop, Color c)
        {
            if (m.HasProperty(prop)) m.SetColor(prop, c);
        }

        private static void SetFloat(Material m, string prop, float f)
        {
            if (m.HasProperty(prop)) m.SetFloat(prop, f);
        }
    }

    /// <summary>The catalogue of cable styles.</summary>
    internal static class CableStyles
    {
        private static List<CableStyle> styles;
        private static Texture2D white;
        private static Material line;

        /// <summary>Bumped whenever the chosen styles or thickness change, so every tether refreshes.</summary>
        public static int Version { get; private set; }

        public static IList<CableStyle> All
        {
            get { if (styles == null) Load(); return styles; }
        }

        public static void NotifyChanged()
        {
            Version++;
        }

        public static void Load()
        {
            styles = new List<CableStyle>();
            ConfigNode[] roots = GameDatabase.Instance != null ? GameDatabase.Instance.GetConfigNodes("KSP_TETHERS") : null;
            if (roots != null && roots.Length > 0)
            {
                foreach (ConfigNode n in roots[0].GetNodes("CABLE_STYLE"))
                {
                    CableStyle s = CableStyle.FromNode(n);
                    if (Get(s.Name, false) == null)
                        styles.Add(s);
                }
            }
            if (styles.Count == 0)
                styles.Add(new CableStyle());
            Version++;
        }

        public static CableStyle Get(string name)
        {
            return Get(name, true);
        }

        private static CableStyle Get(string name, bool fallback)
        {
            if (styles == null)
                Load();
            foreach (CableStyle s in styles)
                if (s.Name == name)
                    return s;
            return fallback && styles.Count > 0 ? styles[0] : null;
        }

        public static CableStyle For(TetherKind kind)
        {
            TetherUserSettings user = TetherUserSettings.Instance;
            return Get(kind == TetherKind.Kerbal ? user.evaStyle : user.cableStyle);
        }

        /// <summary>Generates the textures for the two styles in use, so switching scenes doesn't stutter.</summary>
        public static void PrewarmSelected()
        {
            try
            {
                For(TetherKind.Kerbal).Prewarm();
                For(TetherKind.Vessel).Prewarm();
            }
            catch (Exception e)
            {
                TetherLog.Exception("Generating cable textures", e);
            }
        }

        public static Texture2D White
        {
            get
            {
                if (white == null)
                {
                    white = new Texture2D(4, 4, TextureFormat.RGBA32, false) { name = "KSPTethers-White" };
                    var px = new Color32[16];
                    for (int i = 0; i < px.Length; i++)
                        px[i] = new Color32(255, 255, 255, 255);
                    white.SetPixels32(px);
                    white.Apply(false, true);
                }
                return white;
            }
        }

        /// <summary>Unlit, vertex-coloured material for the aiming line.</summary>
        public static Material LineMaterial
        {
            get
            {
                if (line == null)
                {
                    Shader shader = FindShader("Legacy Shaders/Particles/Alpha Blended", "Particles/Alpha Blended",
                        "Sprites/Default", "KSP/Particles/Alpha Blended", "Unlit/Color");
                    line = new Material(shader) { name = "KSPTethers-Line" };
                    if (line.HasProperty("_TintColor"))
                        line.SetColor("_TintColor", new Color(0.5f, 0.5f, 0.5f, 0.5f));
                }
                return line;
            }
        }

        public static Shader FindShader(params string[] names)
        {
            foreach (string name in names)
            {
                Shader s = Shader.Find(name);
                if (s != null)
                    return s;
            }
            TetherLog.Warn("None of the shaders [" + string.Join(", ", names) + "] were found.");
            return Shader.Find("Hidden/Internal-Colored");
        }
    }
}
